### PR TITLE
upload initial draft python & virtualization intro practicals

### PR DESCRIPTION
**Pull request by PeerHerholz**
- first draft of python intro practicals 
- uploaded in ipynb format to allow easy inspection of code and output
- two parts: working with csv, working with nii
- so far rather rough outline, please feel free to change any part regarding both outline and content

### CODE REVIEW

**Comment by PeerHerholz** [comment]
We could also incorporate some content from the [datacarpentry/python-neuroimaging-lesson](https://github.com/datacarpentry/python-neuroimaging-lesson)!? Thx to @emdupre for the hint!

**Comment by emdupre** [comment]
Thanks so much !! Is this still ok to merge ?

**Comment by PeerHerholz** [comment]
I think so, I created a PR to allow for reviews/comments, but if no one has any, we can go ahead and merge it. I'll redo the notebook, so that it has a bit more comments, etc. .

**Comment by jbpoline** [comment]
Peer, Greg: brainsize.csv does not seem to be in the day2/am directory : should it be or should the notebook be updated ?

**Comment by PeerHerholz** [comment]
Hi @jbpoline, I thought we're uploading all example data (imaging, csv, etc.) to Zenodo. But if not, I'll include it in my PR. I'm very sorry if I missed that change of plans.

**Comment by jbpoline** [comment]
I see - maybe worth putting the link to the data in the notebook

**Comment by PeerHerholz** [comment]
The Zenodo repo does not exist yet, hence I was waiting till does to upload the data. If the Zenodo repo is not happening, I'll put the data in the Github repo. The same holds true for the neuroimaging example dataset.

**Comment by emdupre** [comment]
I don't think it makes sense to use Zenodo at this point for this dataset -- we already asked folks to download [the dataset from OpenNeuro](https://openneuro.org/datasets/ds000007/versions/00001), so putting it there would be asking them to download it twice.

Is the CSV they'll need in that dataset ? If not, maybe we could add it to the GitHub content ?

**Comment by PeerHerholz** [comment]
Sorry, my last update regarding that was that everything data should be uploaded to a Zenodo repo. I did not know that participants were instructed to do so, as I thought we created the version of that dataset with 5 participants in order not require a huge download. It seems like a missed a lot of stuff here, sorry. 

The dataset is not included and I'll include it in this PR.

**Comment by emdupre** [comment]
Sorry for the trouble, but I'm glad we're pining this down ! Thanks for your patience.

What can I do to help ?

**Comment by PeerHerholz** [comment]
No biggie, all good. I'm currently finishing up the virtualization/container notebook and will include that in the PR as well. I should finish the updated version of the python intro one by tomorrow.

**Comment by PeerHerholz** [comment]
Uploaded the virtualization notebook (`venv` to  docker (not included, as Greg will do that)) and updated the python intro notebook (some nice comments still missing, will add them tomorrow). Regarding the latter I also uploaded `brainsize.csv`.

**Comment by jbpoline** [comment]
sounds great ! might be worth saying a word on what is diffusion imaging before going through the notebook

**Pull request merged**
